version: '3'
services:
  ############## nginx ##############
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    depends_on:
      - web
    ports:
      - 80:80

  ############## web ##############
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    command: bundle exec unicorn_rails -p 3000 -c config/unicorn.rb
    volumes:
      - .:/app
    links:
      - redis
      - db
    ports:
      - 3000:3000

  ############## mysql ##############
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd

  ############## redis ##############
  redis:
    image: redis:latest
